"""Pydantic models for structured data contracts across the application."""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field

# --- Tooling Models ---


class DeviceInfo(BaseModel):
    """Data model for a single network device."""

    name: str = Field(..., description="The name of the device.")
    hostname: str = Field(..., description="The IP address or hostname.")
    role: Optional[str] = Field(
        None, description="The role of the device in the network."
    )
    device_type: str = Field(
        ..., description="The Netmiko device type (e.g., cisco_ios)."
    )


class CommandOutput(BaseModel):
    """Structured output for a network command."""

    device_name: str = Field(..., description="The device the command was run on.")
    command: str = Field(..., description="The command that was executed.")
    output: str = Field(..., description="The raw, sanitized output from the device.")
    status: str = Field("success", description="Either 'success' or 'error'.")
    error_message: Optional[str] = Field(
        None, description="Details if an error occurred."
    )


class LogAnalysisOutput(BaseModel):
    """Structured output for a log analysis query."""

    query: str = Field(..., description="The original user query for the logs.")
    relevant_logs: List[str] = Field(
        ..., description="A list of the most relevant log entries found."
    )
    summary: str = Field(
        ..., description="A brief summary of the findings from the logs."
    )


# --- NLP Pre-processing Models ---


class ExtractedEntities(BaseModel):
    """Represents the entities extracted from the user's query."""

    device_names: Optional[List[str]] = Field(
        None, description="A list of device hostnames, like ['S1', 'core-router-gnmi']"
    )
    interfaces: Optional[List[str]] = Field(
        None, description="A list of interface names, like ['GigabitEthernet0/1']"
    )
    protocols: Optional[List[str]] = Field(
        None, description="A list of networking protocols, like ['BGP', 'OSPF']"
    )
    keywords: Optional[List[str]] = Field(
        None, description="Other key terms like 'flaps', 'errors', 'config'"
    )


class UserIntent(BaseModel):
    """The structured representation of a user's request, generated by the NLP layer."""

    query: str = Field(..., description="The original, unmodified user query.")
    intent: Literal[
        "get_status",
        "get_config",
        "find_device",
        "troubleshoot_history",
        "greeting",
        "unknown",
    ] = Field(..., description="The primary goal of the user.")
    entities: ExtractedEntities = Field(
        ..., description="All named entities recognized in the query."
    )
    sentiment: Literal["normal", "urgent", "critical"] = Field(
        "normal", description="The inferred urgency of the user's request."
    )
    is_ambiguous: bool = Field(
        False,
        description="True if the query is unclear or lacks necessary information.",
    )
